/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as SettingsRouteRouteImport } from './../../routes/settings/route'
import { Route as IndexRouteImport } from './../../routes/index'
import { Route as SettingsIndexRouteImport } from './../../routes/settings/index'
import { Route as ProvidersIndexRouteImport } from './../../routes/providers/index'
import { Route as MyUploadsIndexRouteImport } from './../../routes/my-uploads/index'
import { Route as SettingsPresetsRouteImport } from './../../routes/settings/presets'
import { Route as SettingsDatabaseRouteImport } from './../../routes/settings/database'
import { Route as SettingsCompressionRouteImport } from './../../routes/settings/compression'
import { Route as ProvidersProviderIdIndexRouteImport } from './../../routes/providers/$providerId/index'
import { Route as ProvidersProviderIdBucketNameIndexRouteImport } from './../../routes/providers/$providerId/$bucketName/index'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyUploadsIndexRoute = MyUploadsIndexRouteImport.update({
  id: '/my-uploads/',
  path: '/my-uploads/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPresetsRoute = SettingsPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsDatabaseRoute = SettingsDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCompressionRoute = SettingsCompressionRouteImport.update({
  id: '/compression',
  path: '/compression',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ProvidersProviderIdIndexRoute =
  ProvidersProviderIdIndexRouteImport.update({
    id: '/providers/$providerId/',
    path: '/providers/$providerId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProvidersProviderIdBucketNameIndexRoute =
  ProvidersProviderIdBucketNameIndexRouteImport.update({
    id: '/providers/$providerId/$bucketName/',
    path: '/providers/$providerId/$bucketName/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/compression': typeof SettingsCompressionRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/presets': typeof SettingsPresetsRoute
  '/my-uploads': typeof MyUploadsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/providers/$providerId': typeof ProvidersProviderIdIndexRoute
  '/providers/$providerId/$bucketName': typeof ProvidersProviderIdBucketNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/compression': typeof SettingsCompressionRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/presets': typeof SettingsPresetsRoute
  '/my-uploads': typeof MyUploadsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/providers/$providerId': typeof ProvidersProviderIdIndexRoute
  '/providers/$providerId/$bucketName': typeof ProvidersProviderIdBucketNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/compression': typeof SettingsCompressionRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/presets': typeof SettingsPresetsRoute
  '/my-uploads/': typeof MyUploadsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/providers/$providerId/': typeof ProvidersProviderIdIndexRoute
  '/providers/$providerId/$bucketName/': typeof ProvidersProviderIdBucketNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/compression'
    | '/settings/database'
    | '/settings/presets'
    | '/my-uploads'
    | '/providers'
    | '/settings/'
    | '/providers/$providerId'
    | '/providers/$providerId/$bucketName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/compression'
    | '/settings/database'
    | '/settings/presets'
    | '/my-uploads'
    | '/providers'
    | '/settings'
    | '/providers/$providerId'
    | '/providers/$providerId/$bucketName'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/compression'
    | '/settings/database'
    | '/settings/presets'
    | '/my-uploads/'
    | '/providers/'
    | '/settings/'
    | '/providers/$providerId/'
    | '/providers/$providerId/$bucketName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  MyUploadsIndexRoute: typeof MyUploadsIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  ProvidersProviderIdIndexRoute: typeof ProvidersProviderIdIndexRoute
  ProvidersProviderIdBucketNameIndexRoute: typeof ProvidersProviderIdBucketNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-uploads/': {
      id: '/my-uploads/'
      path: '/my-uploads'
      fullPath: '/my-uploads'
      preLoaderRoute: typeof MyUploadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/presets': {
      id: '/settings/presets'
      path: '/presets'
      fullPath: '/settings/presets'
      preLoaderRoute: typeof SettingsPresetsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/database': {
      id: '/settings/database'
      path: '/database'
      fullPath: '/settings/database'
      preLoaderRoute: typeof SettingsDatabaseRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/compression': {
      id: '/settings/compression'
      path: '/compression'
      fullPath: '/settings/compression'
      preLoaderRoute: typeof SettingsCompressionRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/providers/$providerId/': {
      id: '/providers/$providerId/'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof ProvidersProviderIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$providerId/$bucketName/': {
      id: '/providers/$providerId/$bucketName/'
      path: '/providers/$providerId/$bucketName'
      fullPath: '/providers/$providerId/$bucketName'
      preLoaderRoute: typeof ProvidersProviderIdBucketNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsCompressionRoute: typeof SettingsCompressionRoute
  SettingsDatabaseRoute: typeof SettingsDatabaseRoute
  SettingsPresetsRoute: typeof SettingsPresetsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsCompressionRoute: SettingsCompressionRoute,
  SettingsDatabaseRoute: SettingsDatabaseRoute,
  SettingsPresetsRoute: SettingsPresetsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  MyUploadsIndexRoute: MyUploadsIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  ProvidersProviderIdIndexRoute: ProvidersProviderIdIndexRoute,
  ProvidersProviderIdBucketNameIndexRoute:
    ProvidersProviderIdBucketNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
